### PR TITLE
Fix disqus background in dark mode.

### LINKED ISSUE #722: Disqus renders horribly
Hello!

I tried enabling Disqus, and it renders horribly. The Disqus theme is set to "auto".

image

Any pointers?

Thanks

### PR DESCRIPTION
**Pull request by xiaotianxt**
### Prerequisites

- [x] This pull request fixes a bug.
- [x] This pull request adds a feature.
- [ ] This pull request introduces breaking change.

### Description

This PR fixes the bug about disqus iframe background in dark mode, it also fix another bug when switching color mode.

Before:
opaque background in dark mode

After:
CleanShot 2022-11-20 at 01 12 52@2x

#### Why this happens

The problem is widely discussed [here](https://github.com/w3c/csswg-drafts/issues/4772). 

>If the color scheme of an iframe differs from embedding document, iframe gets an opaque canvas bg appropriate to its color scheme.

So I made two fixes:

1. Add `color-scheme: light` CSS property for disqus `iframe`, this creates a transparent background and fixes the opaque issue.
2. Add `themeChanged` event to notice disqus comments board refresh when the theme change, this fixes the opaque problem when you switch the mode.

#### Reference

I've been working on this issue for a whole night and the fixing idea was strongly inspired by [Sergeyski's Blog](https://sergeyski.com/css-color-scheme-and-iframes-lessons-learned-from-disqus-background-bug/).

### Issues Resolved

Fixes #722.

### CODE REVIEW

File: assets/js/coder.js [hunk 1]
```diff
@@ -76,6 +76,9 @@ function setTheme(theme) {
         
     }
     
+    // Create and send event
+    const event = new Event('themeChanged');
+    document.dispatchEvent(event);
```
Comment (luizdepra) [inline assets/js/coder.js:81]: I need to refactor every comment system integration to use events too. This look way nicer.

**Comment by luizdepra** [comment]
Nice. Thank you. :)

**Review by luizdepra — APPROVED** [review]
